### ISSUE TITLE
Improve outline rendering

### ISSUE THREAD

**Issue by RosaWagner** [cbcrc/radiocanadafonts#64]
Rendering can be improved by avoiding overlapping segments which sharpen pixels on edges.

<img width="852" alt="Capture d’écran 2022-03-02 à 14 39 43" src="https://user-images.githubusercontent.com/12222436/156374338-45c36859-de54-4bb2-bdcb-463900e0c7ef.png">

<img width="638" alt="Capture d’écran 2022-03-02 à 14 52 43" src="https://user-images.githubusercontent.com/12222436/156374718-af5b6e01-a150-4d15-8606-1cfa9d87d4e2.png">

**Comment by t1gu1** [comment]
It's small but there is an example of what I can see on my Mac/Chrome on each 3px. (More visible under 100px of size)
Pretty sure that will fix my T issue.

![image](https://user-images.githubusercontent.com/12479055/203865363-e4195e09-910d-4f17-b3d7-e4fde313bc67.png)
