### ISSUE TITLE
Missing character: ʕ

### ISSUE THREAD

**Issue by crsaila** [cbcrc/radiocanadafonts#73]
One of our producers reported that a character in our roman/italic fonts does not render: the pharyngeal voiced fricative, ʕ - [Wiki reference](https://en.wikipedia.org/wiki/Voiced_pharyngeal_fricative) 

This is commonly seen in Indigenous names we reference. An example is: n'Kiʕəmc'n

As near as I can tell, this doesn't fall in the supported Unicode sets, but was wondering if it would be an easy addition to the set

**Comment by Fonthausen** [comment]
Hi Craig,
I have had a look in the fonts, but the the pharyngeal voiced fricative, ʕ, is actually in the font. With the corresponding unicode. In the wiki page you referred, you can see the unicode on thee right side.

<img width="1198" alt="Schermafbeelding 2022-04-20 om 22 16 00" src="https://user-images.githubusercontent.com/20181530/164316287-388b89a6-833f-417b-b09d-c054a9a911c2.png">

**Comment by crsaila** [comment]
Ah great - we’ve been looking at v2.1 (released Dec) so perhaps the mapping is wrong on that. When I tested that release in both a doc and Fontbook it wasn’t rendering.

**Comment by crsaila** [comment]
Confirmed after a clean reinstall of the latest version typeface that the character rendered as intended. Thanks!

(Also checked this version against a (story about Indigenous names)[https://www.cbc.ca/news/canada/british-columbia/indigenous-names-vital-stats-1.6426239] not being recognized by the government - and all characters rendered using Radio-Canada as expected.)
