### ISSUE TITLE
accents width to fix

### ISSUE THREAD

**Issue by RosaWagner** [cbcrc/radiocanadafonts#75]
- legacy accents should not have width = 0
- Only comb accents should have width=0 in binaries, and this is handled during export by the building tools

@Fonthausen, can you re-add width to all accents and set up legacy accents as components of comb accents. They also should not be used as components in accented glyphs: `igrave` is currently composed with `grave` instead of `gravecomb`.

This way the GDEF table can be properly written during generation.

We noticed a display issue on GF with grave accent from keyboard, I would like to make sure this issue doesn't occur because of problem what mentioned above.

<img width="1460" alt="Capture d’écran 2022-04-28 à 17 58 02" src="https://user-images.githubusercontent.com/12222436/165794738-677db901-b5cb-4470-94f2-0f902074d7cc.png">

**Comment by Fonthausen** [comment]
– Use of legacy accents checked and corrected.
– Re-generated legacy accents as components from comb_accents.
– Width legacy accents set to 500 units and centered components.
