### ISSUE TITLE
other case sensitive accents issues

### ISSUE THREAD

**Issue by RosaWagner** [cbcrc/radiocanadafonts#78]
`circumflexcomb.case` and `caroncomb.case` are reverted. Sorry I may have done that while auto-renaming accents in my last PR.

This does not matter much since these glyphs are not currently used in uppercase letters. Which brings to the other issue: .case accents are not consistently used in uppercase letters. Are they different from the lowercase accents? If not, we may as well remove the useless ones.

cc @Fonthausen

**Comment by Fonthausen** [comment]
I originally didn't touch those, since my assignment was to work on the latinized indigenous script. In the Italic there are only two .case accents. 

You can delete the unused ones if you want. Depending on how much time I will have after finishing the Inuktituk, I might have a better look.

**Comment by RosaWagner** [comment]
Okay, after checking there was no difference between the case accents, and the lowercase one (except for ring acute). I removed the unused ones. My PR is now good to merge.

**Comment by Fonthausen** [comment]
Merged.
